### ISSUE TITLE
Manh - add Form LyLichKhoaHoc

### ISSUE THREAD

**Issue by HoangtuVungxa** [HoangtuVungxa/QuanLyDeTaiKhoaHoc#14]
Chức năng Thêm, Sửa, Xoá, Lưu lý lịch khoa học của các tác giả; Đóng form

**Comment by NguyenQuocManhCN12** [comment]
Em them form Ly lich khoa hoc roi nhe! Anh Linh check giup em

**Comment by HoangtuVungxa** [comment]
ok de kiem tra
