### ISSUE TITLE
Tuan - add Form BaoCao and Form TacGiaDeTai

### ISSUE THREAD

**Issue by HoangtuVungxa** [HoangtuVungxa/QuanLyDeTaiKhoaHoc#9]
Form BaoCao Báo cáo tình hình nghiên cứu khoa học
Form TacGiaDeTai: thêm sửa xoá lưu các thành viên trong đề tài, đóng form

**Comment by shinichiok2614** [comment]
i just add form BC and form TGDT.

**Comment by HoangtuVungxa** [comment]
ok. let me check this
